### ISSUE TITLE
Is  `fromTokenId_;` code redundant in `_createDerivedTokenId` function?

### ISSUE THREAD

**Issue by waheya** [solv-finance/erc-3525#13]
Is  `fromTokenId_;` code redundant in `_createDerivedTokenId` function?
Just like the follow code in ERC3525.sol:
```
function _createDerivedTokenId(uint256 fromTokenId_) internal virtual returns (uint256) {
        fromTokenId_;
        return _createOriginalTokenId();
    }
```

**Comment by YeeTsai** [comment]
In some scenarios,  the derived token id needs to be related to the from token id in the split action ( transfer some value to address from Id ).   _createDerivedTokenId function is a reserved extension for this case. So, It is necessary to keep the fromTokenId.
